### ISSUE TITLE
Release a new version to avoid deprecation message?

### ISSUE THREAD

**Issue by addaleax** [novemberborn/package-hash#34]
Hey! Would it be possible to release a new version of this module? That should make some deprecation warnings that you’ll be getting once `new Buffer()` prints those go away. :)

**Comment by novemberborn** [comment]
Yea, good idea. We should replace the `Buffer` usage. We'll have to push it out as a breaking change since this package is used in AVA version that target Node.js < 4.5.

Happy to take a PR since I might not get round to doing this for a while yet.

**Comment by addaleax** [comment]
@novemberborn I think you really just need to publish a new version here? It won’t support those versions of Node, but I think that’s fine. If you run old v4.x versions, you have security issues anyway, *and* Node 4 is going EOL in a month, meaning that it should be safe for people to upgrade to a major `package-hash` release very soon.

**Comment by novemberborn** [comment]
> I think you really just need to publish a new version here?

Oh yea, looks like I did make the changes already! Though I suspect nyc and AVA may still be on the 1.0 release.

**Comment by coreyfarrell** [comment]
@novemberborn I think this can be closed now too.  Thanks for publishing the new release!
