### ISSUE TITLE
Require node.js 8?

### ISSUE THREAD

**Issue by coreyfarrell** [novemberborn/package-hash#40]
Hi @novemberborn, before I bother preparing a PR I wanted to ask you are for or against dropping node.js 6.  This module and caching-transform both require `hasha` and the latest version requires node.js 8.

**Comment by novemberborn** [comment]
Yea that's fine, Node.js 6 is going out of maintenance mode real soon now anyway. Just need to bump the major version. See also https://github.com/avajs/ava/blob/master/docs/support-statement.md.

I'll add you to this repo and npm.

**Comment by coreyfarrell** [comment]
Node.js 6 hit EOL on April 1st (no fooling).  Thanks for the add, I'll post a PR for the update, I still like to get a sanity check, especially before posting to npm.  Once the PR gets a +1 I can merge and release.

Side question: this repo doesn't have any Changelog, is this intentional?  I see that `ava` has [release notes](https://github.com/avajs/ava/releases) in github.  I've never used 'github releases', any docs/pointers on the correct process to do that?  I suppose a benefit of this over generating a CHANGELOG.md is smaller npm installs?  Without answers it looks like following the existing process for package-hash would be to manually bump package.json / package-lock.json version to 4.0.0, `git commit -m '4.0.0' && git tag -s v4.0.0 -m 4.0.0  && git push origin --follow-tags`.

**Comment by novemberborn** [comment]
> Node.js 6 hit EOL on April 1st (no fooling).

Oh I hadn't even realized. Figured it'd be later in the month. Happy days!



> Once the PR gets a +1 I can merge and release.

👍 



> Side question: this repo doesn't have any Changelog, is this intentional? I see that `ava` has [release notes](https://github.com/avajs/ava/releases) in github. I've never used 'github releases', any docs/pointers on the correct process to do that? I suppose a benefit of this over generating a CHANGELOG.md is smaller npm installs? Without answers it looks like following the existing process for package-hash would be to manually bump package.json / package-lock.json version to 4.0.0, `git commit -m '4.0.0' && git tag -s v4.0.0 -m 4.0.0 && git push origin --follow-tags`.

I usually publish through [`np`](https://www.npmjs.com/package/np), e.g. `npx np major`. That updates the version number and pushes the tags. Then for larger packages I'll do a GitHub release for that tag. For smaller ones I tend not to bother, it's clear enough if you look at the commit history.

**Comment by coreyfarrell** [comment]
package-hash@4.0.0 is now published

**Comment by coreyfarrell** [comment]
:angry: apparently the node.js 6 EOL date was changed 3 weeks ago - https://github.com/nodejs/Release/pull/425/files?file-filters%5B%5D=.json.  Sorry I didn't recheck the release date before telling you it was April 1st.  Just wanted to let you know in case it changes your plans for other packages.

**Comment by novemberborn** [comment]
> Just wanted to let you know in case it changes your plans for other packages.

Thanks 😄 But regardless it's close enough that dropping support is fine.
